Added automatic recovery and removed ffmpeg banner to clean up logs and added validation check for STREAM_INPUT

diff --git a/docker-ffmpeg b/docker-ffmpeg
--- a/docker-ffmpeg
+++ b/docker-ffmpeg
@@ -1,6 +1,10 @@
 #!/bin/ash
 # FFMPEG Launcher
 
+echo ""
+echo "$(date) - Docker Launch"
+echo ""
+
 # TZ SET - Requires tzdata package
 if [[ "$TZ" == "" ]]; then
     echo timezone not defined using ENV 'TZ', using UTC.
@@ -26,23 +30,32 @@ if [ ! -e /output/tmp ]; then
     mkdir /output/tmp
 fi
 
-# Cleanup premature exits from previous runs
-if [ $(ls /output/tmp | wc -l) -ne 0 ]; then
-    for file in $(ls /output/tmp); do
-        # Create Directory if not exists
-        if [ ! -e /output/$(echo $file | cut -d_ -f2 | cut -d- -f1)/$(echo $file | cut -d_ -f2 | cut -d- -f2)/$(echo $file | cut -d_ -f2 | cut -d- -f3)/$(echo $file | cut -d_ -f3 | cut -d- -f1) ]; then
-            mkdir -p /output/$(echo $file | cut -d_ -f2 | cut -d- -f1)/$(echo $file | cut -d_ -f2 | cut -d- -f2)/$(echo $file | cut -d_ -f2 | cut -d- -f3)/$(echo $file | cut -d_ -f3 | cut -d- -f1)
-        fi
-        # Convert TS to MP4
-        ffmpeg -i /output/tmp/$file -c copy /output/$(echo $file | cut -d_ -f2 | cut -d- -f1)/$(echo $file | cut -d_ -f2 | cut -d- -f2)/$(echo $file | cut -d_ -f2 | cut -d- -f3)/$(echo $file | cut -d_ -f3 | cut -d- -f1)/$(echo $file | cut -d. -f1).mp4
-        ffprobe /output/tmp/$file 2&>/dev/null && rm /output/tmp/$file || echo "Temporary file not deleted because final file is corrupt - /output/tmp/$file"
-    done
+if [[ "${INPUT_STREAM}" == "" ]]; then
+    echo "$(date) - INPUT_STREAM is required.  Exiting."
+    exit 1
 fi
 
 docker-ffmpeg-watcher &
 
-echo "$(date) - Processing Started."
-ffmpeg -analyzeduration 60 -probesize 50000000 -fflags discardcorrupt+genpts+nobuffer+autobsf -f rtsp -rtsp_transport tcp -stimeout 5000000 -re -err_detect ignore_err -i ${INPUT_STREAM} -flags +global_header -c copy -f segment -segment_time ${SEGMENT_TIME} -segment_atclocktime 1 -segment_format ${SEGMENT_FORMAT} -strftime 1 /output/tmp/${OUTPUT_PREFIX}_%Y-%m-%d_%H-%M-%S_%Z.ts
-echo "$(date) - Processing Complete."
+while true; do
+    # Cleanup premature exits from previous runs
+    if [ $(ls /output/tmp | wc -l) -ne 0 ]; then
+        for file in $(ls /output/tmp); do
+            # Create Directory if not exists
+            if [ ! -e /output/$(echo $file | cut -d_ -f2 | cut -d- -f1)/$(echo $file | cut -d_ -f2 | cut -d- -f2)/$(echo $file | cut -d_ -f2 | cut -d- -f3)/$(echo $file | cut -d_ -f3 | cut -d- -f1) ]; then
+                mkdir -p /output/$(echo $file | cut -d_ -f2 | cut -d- -f1)/$(echo $file | cut -d_ -f2 | cut -d- -f2)/$(echo $file | cut -d_ -f2 | cut -d- -f3)/$(echo $file | cut -d_ -f3 | cut -d- -f1)
+            fi
+            # Convert TS to MP4
+            echo "$(date) - Starting Processing of Previous Temporary File - $file"
+            ffmpeg -hide_banner -fflags discardcorrupt -err_detect ignore_err -i /output/tmp/$file -c copy /output/$(echo $file | cut -d_ -f2 | cut -d- -f1)/$(echo $file | cut -d_ -f2 | cut -d- -f2)/$(echo $file | cut -d_ -f2 | cut -d- -f3)/$(echo $file | cut -d_ -f3 | cut -d- -f1)/$(echo $file | cut -d. -f1).mp4
+            ffprobe /output/tmp/$file 2&>/dev/null && rm /output/tmp/$file || echo "Temporary file not deleted because final file is corrupt - /output/tmp/$file"
+            echo "$(date) - Completed Processing File - $file"
+        done
+    fi
 
+    echo "$(date) - Processing Started."
+    ffmpeg -analyzeduration 60 -probesize 50000000 -fflags discardcorrupt+genpts+nobuffer+autobsf -f rtsp -rtsp_transport tcp -stimeout 5000000 -re -err_detect ignore_err -i ${INPUT_STREAM} -flags +global_header -movflags frag_keyframe+empty_moov+default_base_moof+rtphint -c copy -f segment -segment_time ${SEGMENT_TIME} -segment_atclocktime 1 -segment_format ${SEGMENT_FORMAT} -strftime 1 /output/tmp/${OUTPUT_PREFIX}_%Y-%m-%d_%H-%M-%S_%Z.ts
+    echo "$(date) - Processing Exit."
+    sleep 5
+done
 exit 0
